### ISSUE TITLE
Dataset RPLAN JSON 

### ISSUE THREAD

**Issue by albertotono** [aminshabani/house_diffusion#16]
I was able to convert the RPLAN to the JSON format, the process it is quite long, 

Is it possible to share here the folder since it is only 65MB (.zip) or are there any copyright issues involved? 
If anyone need it, feel free to reach out.

Best Regards

**Comment by albertotono** [comment]
just check with the main authors first and CC me, then I am happy to share the dataset with you if the main owner of the dataset are ok.

**Comment by Yovecent** [comment]
> just check with the main authors first and CC me, then I am happy to share the dataset with you if the main owner of the dataset are ok.
Hello, can you explain the meaning of "edges" and "ed_rm" in the example below? Thank you !!
I just dont know the meaning of the 4th and 5th number in per list of the "edges" and the what's the difference between the two number in "edges" and "ed_rm。Thanks！！
```
#first four entry are per list are rooms edges and 4th and 6th are showing what room type is on each side of edge 
"edges":[72.0, 161.0, 72.0, 220.0, 3, 0], ...,[107.0, 130.0, 72.0, 130.0, 4, 0], [148.0, 28.0, 148.0, 87.0, 1, 2]] 

#room indexes that are on each side of the edges
"ed_rm":[0], [0], [0], [0, 2], ..., [2], [2, 3], [2, 1], [2, 0], [2]] 
```

**Comment by yangfy2023** [comment]
> just check with the main authors first and CC me, then I am happy to share the dataset with you if the main owner of the dataset are ok.

May I ask for the json processed dataset?
or How to process the failed_rplan_json?
