### ISSUE TITLE
dataset problem ,plz

### ISSUE THREAD

**Issue by liey1** [aminshabani/house_diffusion#2]
hello，I see that the code uses the file 'list.txt', but I do not know what format it is，I tried to extract the dataset, but I am a beginner and do not know how to do it.，can you provide rplan floders？plz，it's my homework

**Comment by aminshabani** [comment]
Hi, unfortunately due to copywrite concerns, we are not allowed to publicly provide the RPLAN dataset. However, `list.txt` is simply a txt file including the name of the houses. Please see [here](https://github.com/aminshabani/diffusion_project/blob/master/guided_diffusion/rplanhg_datasets.py#L122) and [here](https://github.com/sepidsh/Housegan-data-reader).

**Comment by antutwo** [comment]
hello,Do you have the running result of this? Can you give me a screenshot of the result? We want to see the running result. This is about our homework.

**Comment by aminshabani** [comment]
Hi, what do you mean by the running result? if you mean RPLAN dataset, there is a sample output in [this](https://github.com/sepidsh/Housegan-data-reader) repository.

**Comment by SuroshAhmadZobair** [comment]
@aminshabani 
Thanks for your effort on this great repo. 
I still can't quite understand how to create list.txt. I have looked at the links you provided, but I am still struggling with it. 
here is how my` list.txt` looks like. 
```
ROOM_CLASS = {"living_room": 1, "kitchen": 2, "bedroom": 3, "bathroom": 4, "balcony": 5, "entrance": 6, "dining room": 7, "study room": 8,
              "storage": 10 , "front door": 15, "unknown": 16, "interior_door": 17}

```

How should I change it?

Thanks in advance!

**Comment by SuroshAhmadZobair** [comment]
I got it. 
it is simply the filename of the JSON files, not the name of the houses!
```
1.json
2.json
.....
1000.json
```

**Comment by Yovecent** [comment]
> I got it. it is simply the filename of the JSON files, not the name of the houses!
> 
> ```
> 1.json
> 2.json
> .....
> 1000.json
> ```

Hello, can you explain the meaning of "edges" and "ed_rm"for me ? Thank you !!

```
#first four entry are per list are rooms edges and 4th and 6th are showing what room type is on each side of edge 
"edges":[72.0, 161.0, 72.0, 220.0, 3, 0], ...,[107.0, 130.0, 72.0, 130.0, 4, 0], [148.0, 28.0, 148.0, 87.0, 1, 2]] 

#room indexes that are on each side of the edges
"ed_rm":[0], [0], [0], [0, 2], ..., [2], [2, 3], [2, 1], [2, 0], [2]] 
```
