### ISSUE TITLE
Regarding the requirement of the number of rooms

### ISSUE THREAD

**Issue by QianyiWu** [aminshabani/house_diffusion#3]
Hi,

Congrats on your excellent work acceptance! I came across your code and noticed that the model will be trained with a specific number of rooms. 
https://github.com/aminshabani/house_diffusion/blob/24ff52cd945ea2b425a4652e826c9d88d7c0330d/house_diffusion/rplanhg_datasets.py#L124
I am curious whether a trained model can also be used for generating another number of rooms during inference. Should it be possible if we change the self_mask, door_mask and gen_mask according to the input bubble diagram?

**Comment by aminshabani** [comment]
Hi, thank you for your interest in our work! 
Yes, that should be fine and we actually do the same. You just need to provide the corresponding input to the model as you mentioned. In our rplan loader, `target_set` is the number of rooms.
