### ISSUE TITLE
Test Json

### ISSUE THREAD

**Issue by sakmalh** [aminshabani/house_diffusion#4]
I really like the work and congrats to you for making a huge improvement from HouseGAN++ to this. 

I forked the code and got it to work locally. The sample and the train. Again thanks for providing the model for using to sample as well. I tried sampling from the rplan dataset and it works fine. But I want to have a custom json. With room types and the adjacency given. But not the coordinates. I noticed we can also add number of corners.

Can I have an example on how a custom json would look like so I can customize it per user requirements. 

Thank you

**Comment by aminshabani** [comment]
Thank you for your interest in our work, unfortunately I don't have any sample json for that part as the original data loader needs additional information such as the room boundaries. However, you can change the "eval" part of the data loader to select your manual number of corners instead of the random selection. You can find it [here](https://github.com/aminshabani/house_diffusion/blob/main/house_diffusion/rplanhg_datasets.py#L257).

**Comment by sakmalh** [comment]
I actually noted that part from your research paper. I don't think number of corners would be ideal for what I am planning to do. I need to make an improvement in your research and create a web application so a user can specify room types and numbers and it generates accordingly. Let me know if you have any suggestions. Would help me a lot. Thanks again

**Comment by SuroshAhmadZobair** [comment]
Hi @sakmalh 

Have you managed to create your custom json given room_types?

**Comment by sakmalh** [comment]
@SuroshAhmadZobair Looks like we can't do custom room types the way he has configured. What I did was store the Jsons as documents in mongodb and query the given room types and numbers and generate it. The problem is we can only generate specific house layouts given in the dataset. The thing we could do is change the number of corners of each room to provide unique rooms. 

Downside is like I said we can't generate a layout with 2 living rooms and 4 rooms cause we don't have a layout like that in our dataset.

**Comment by sakmalh** [comment]
@SuroshAhmadZobair let me know if you find a better way.

**Comment by SuroshAhmadZobair** [comment]
@sakmalh 
Your method might work well in specific scenarios, but as you mentioned it comes with a lousy trade-off. 
Maybe we can train a regression model to be able to predict the coordinates of the missing corners to compensate for the lack of layout diversity in the dataset.

Thanks for your work on the forked repo.

**Comment by sakmalh** [comment]
@SuroshAhmadZobair That works as well. As I think of it. tbh I am not really an expert in Machine Learning but I know how to work around things, If you like we can collaborate and try it out. I am doing this for my final year project.
