### ISSUE TITLE
Sampling from pre-trained model

### ISSUE THREAD

**Issue by Fatemeh-Mostafavi** [aminshabani/house_diffusion#9]
Hi, 
I'm trying to sample from the pre-trained model (model250000.pt). I get these msgs in the terminal and it seems to take a very long time. Any suggestions? Nothing is saved in the output folders.

Logging to ckpts\openai_2023_07_24_10_52_37_162253
creating model and diffusion...
Number of model parameters: 26541330
COSINE
sampling...
loading eval of target set 8

**Comment by ubaidullaazeem** [comment]
@Fatemeh, For me also getting the same. Can you please help me how to fix this?
